"""Mod Organizer omod Installer

A Python plugin for Mod Organizer 2 which installs omod files generated by
Oblivion Mod Manager.
"""

__author__ = "Mark Kozlov"
__license__ = "MIT"
__version__ = "0.1.0"
